export const FETCH_REQUEST = 'FETCH_REQUEST';
export const FETCH_REQUEST_SUCCESS = 'FETCH_REQUEST_SUCCESS';
export const FETCH_REQUEST_FAILURE = 'FETCH_REQUEST_FAILURE';
export const HIDE_BUTTON = 'HIDE_BUTTON';
export const SEND_REQUEST_SUCCESS = 'SEND_REQUEST_SUCCESS';
export const FETCH_REQUEST_MODAL = 'FETCH_REQUEST_MODAL';
export const SHOW_MODAL = 'SHOW_MODAL';
