export const FETCH_REQUEST = "FETCH_REQUEST";
export const FETCH_REQUEST_SUCCESS = "FETCH_REQUEST_SUCCESS";
export const FETCH_REQUEST_ERROR = "FETCH_REQUEST_ERROR";
export const SHOW_MODAL = "SHOW_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";
